# Generated by Django 5.2.5 on 2025-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='sample image.jpeg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
